# Dirección de la base de datos (asegúrate que el puerto sea 5432)
spring.datasource.url=jdbc:postgresql://localhost:5432/historias_usuario
spring.datasource.username=postgres
spring.datasource.password=root

# Hibernate creará la tabla 'personas' automáticamente basándose en tu PersonaEntity
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect