<<<<<<< HEAD
# Dirección de la base de datos (asegúrate que el puerto sea 5432)
spring.datasource.url=jdbc:postgresql://localhost:5432/historias_usuario
spring.datasource.username=postgres
spring.datasource.password=root

# Hibernate creará la tabla 'personas' automáticamente basándose en tu PersonaEntity
=======

spring.datasource.url=jdbc:postgresql://localhost:5432/registro_db
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver


>>>>>>> a8ea7699432f1f1c24ac75bcdcfd5f6724186363
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect